### ISSUE TITLE
Game Services Crashing

### ISSUE THREAD

**Issue by darkpolice** [TeamKarbonOfficial/Duo_Run#2]
When PREF_WAS_OFFLINE == true, this happens. Yay HAHA
```
01-26 20:30:06.524  10567-10593/com.teamkarbon.android.duo_run.android E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 2346
    Process: com.teamkarbon.android.duo_run.android, PID: 10567
    java.lang.IllegalStateException: Number of steps must be greater than 0
            at android.os.Parcel.readException(Parcel.java:1486)
            at android.os.Parcel.readException(Parcel.java:1427)
            at com.google.android.gms.games.internal.IGamesService$Stub$Proxy.a(Unknown Source)
            at com.google.android.gms.games.internal.GamesClientImpl.a(Unknown Source)
            at com.google.android.gms.games.internal.api.AchievementsImpl$6.a(Unknown Source)
            at com.google.android.gms.games.internal.api.AchievementsImpl$6.a(Unknown Source)
            at com.google.android.gms.common.api.BaseImplementation$a.b(Unknown Source)
            at com.google.android.gms.common.api.b.a(Unknown Source)
            at com.google.android.gms.common.api.b.b(Unknown Source)
            at com.google.android.gms.games.internal.api.AchievementsImpl.increment(Unknown Source)
            at com.teamkarbon.android.duo_run.android.AndroidLauncher.submitInAchievements(AndroidLauncher.java:255)
            at com.teamkarbon.android.duo_run.derptest.render(derptest.java:679)
            at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:416)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by darkpolice** [comment]
It appears this is causing the problem.

```
submitInAchievements(String id, int number)
```

For now, I have commented out those stuff, so that it wouldn't crash

**Comment by darkpolice** [comment]
Ok, whut LOL... Kinda fixed it although it doesn't make sense :/
